### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 13120241790** [lixiaodaoaaa/upload_single_aar2maven#1]
Execution failed for task ':platform_oppo:publishMavenJavaPublicationToMavenRepository'.
> Failed to publish publication 'mavenJava' to repository 'maven'
   > Invalid publication 'mavenJava': artifact file does not exist: '/Users/macbook/Documents/julive/library/Push_v3/platform_oppo/libs/com.heytap.msp-push-2.1.0.aar.aar'

**Comment by lixiaodaoaaa** [comment]
你的文件不存在，请确保这个文件存在
*/Users/macbook/Documents/julive/library/Push_v3/platform_oppo/libs/com.heytap.msp-push-2.1.0.aar.aar*
